"""face_encodings field changes.

Revision ID: caab5af7ffa1
Revises: c85ee7e79351
Create Date: 2024-02-29 06:32:29.577617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caab5af7ffa1'
down_revision: Union[str, None] = 'c85ee7e79351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
